export const palette = {
  /* Gray Scale */
  '--base-hue-gray': '234',
  '--base-gray': 'var(--base-hue-gray) 59%',
  '--palette-gray-00': 'var(--base-gray) 100%',
  '--palette-gray-01': 'var(--base-gray) 99%',
  '--palette-gray-01-5': 'var(--base-gray) 98.5%',
  '--palette-gray-02': 'var(--base-gray) 98%',
  '--palette-gray-03': 'var(--base-gray) 97%',
  '--palette-gray-05': 'var(--base-gray) 95%',
  '--palette-gray-07': 'var(--base-gray) 93%',
  '--palette-gray-08': 'var(--base-gray) 92%',
  '--palette-gray-09': 'var(--base-gray) 91%',
  '--palette-gray-10': 'var(--base-gray) 90%',
  '--palette-gray-15': 'var(--base-gray) 85%',
  '--palette-gray-20': 'var(--base-gray) 80%',
  '--palette-gray-25': 'var(--base-gray) 75%',
  '--palette-gray-30': 'var(--base-gray) 70%',
  '--palette-gray-35': 'var(--base-gray) 65%',
  '--palette-gray-40': 'var(--base-gray) 60%',
  '--palette-gray-45': 'var(--base-gray) 55%',
  '--palette-gray-50': 'var(--base-gray) 50%',
  '--palette-gray-55': 'var(--base-gray) 45%',
  '--palette-gray-60': 'var(--base-gray) 40%',
  '--palette-gray-65': 'var(--base-gray) 35%',
  '--palette-gray-70': 'var(--base-gray) 30%',
  '--palette-gray-75': 'var(--base-gray) 25%',
  '--palette-gray-80': 'var(--base-gray) 20%',
  '--palette-gray-85': 'var(--base-gray) 15%',
  '--palette-gray-88': 'var(--base-gray) 12%',
  '--palette-gray-90': 'var(--base-gray) 10%',
  '--palette-gray-95': 'var(--base-gray) 5%',
  '--palette-gray-98': 'var(--base-gray) 2%',
  '--palette-gray-100': 'var(--base-gray) 0%',
 
  /* Blue Scale */
  '--base-brand-blue': '234',
  '--base-blue': 'var(--base-brand-blue) 60%',
  '--palette-blue-00': 'var(--base-blue) 100%',
  '--palette-blue-05': 'var(--base-blue) 95%',
  '--palette-blue-10': 'var(--base-blue) 90%',
  '--palette-blue-15': 'var(--base-blue) 85%',
  '--palette-blue-20': 'var(--base-blue) 80%',
  '--palette-blue-25': 'var(--base-blue) 75%',
  '--palette-blue-30': 'var(--base-blue) 70%',
  '--palette-blue-35': 'var(--base-blue) 65%',
  '--palette-blue-40': 'var(--base-blue) 60%',
  '--palette-blue-45': 'var(--base-blue) 55%',
  '--palette-blue-50': 'var(--base-blue) 50%',
  '--palette-blue-55': 'var(--base-blue) 45%',
  '--palette-blue-60': 'var(--base-blue) 40%',
  '--palette-blue-65': 'var(--base-blue) 35%',
  '--palette-blue-70': 'var(--base-blue) 30%',
  '--palette-blue-75': 'var(--base-blue) 25%',
  '--palette-blue-80': 'var(--base-blue) 20%',
  '--palette-blue-85': 'var(--base-blue) 15%',
  '--palette-blue-90': 'var(--base-blue) 10%',
  '--palette-blue-95': 'var(--base-blue) 5%',
};
